In [15]:
from skimage.feature import hog
import joblib,glob,os,cv2

from sklearn.svm import LinearSVC
from sklearn.model_selection import train_test_split
from sklearn import svm
import numpy as np 
from sklearn.preprocessing import LabelEncoder
from matplotlib import pyplot as plt

In [16]:

from google.colab import drive

drive.mount('/content/gdrive/', force_remount=True)

Mounted at /content/gdrive/


In [17]:
X = []
Y = []

In [18]:
pos_im_path = '/content/gdrive/MyDrive/cv project/dataset/1'
neg_im_path = '/content/gdrive/MyDrive/cv project/dataset/0'


In [19]:
 # Load the positive features
for filename in glob.glob(os.path.join(pos_im_path,"*.png")):
     fd = cv2.imread(filename,0)
     fd = cv2.resize(fd,(64,128))
     fd = hog(fd,orientations=9,pixels_per_cell=(8,8),visualize=False,cells_per_block=(3,3))
     X.append(fd)
     Y.append(1)

In [20]:
 # Load the negative features
for filename in glob.glob(os.path.join(neg_im_path,"*.png")):
     fd = cv2.imread(filename,0)
     fd = cv2.resize(fd,(64,128))
     fd = hog(fd,orientations=9,pixels_per_cell=(8,8),visualize=False,cells_per_block=(3,3))
     X.append(fd)
     Y.append(0)

In [27]:
X = np.float32(X)
Y = np.array(Y)

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2)

print('Train Data:',len(X_train))
print('Train Labels (1,0)',len(y_train))

Train Data: 736
Train Labels (1,0) 736


In [33]:
print(X_train)

print(y_train)

[[0.29396534 0.17843413 0.05072529 ... 0.07233419 0.26661283 0.23672467]
 [0.11828806 0.03899466 0.08516556 ... 0.28137538 0.04598231 0.18787381]
 [0.09203349 0.07299364 0.09830321 ... 0.22280617 0.18891925 0.21777648]
 ...
 [0.23549888 0.03642983 0.0704293  ... 0.02844971 0.06189633 0.25960264]
 [0.24034353 0.11358801 0.0467008  ... 0.00676802 0.01751661 0.03282871]
 [0.1543025  0.         0.08579985 ... 0.01497996 0.07243107 0.18701726]]
[0 1 1 0 1 1 1 1 1 1 1 1 1 0 1 1 0 1 0 0 0 0 0 0 0 0 1 0 1 1 1 0 1 1 1 1 0
 0 0 0 0 1 1 0 1 0 0 1 1 1 1 0 0 1 1 1 0 1 0 1 0 1 0 0 0 1 0 0 0 1 1 0 0 1
 1 0 1 0 0 1 1 1 1 1 1 1 1 1 0 1 1 0 0 0 1 1 0 1 1 0 1 1 0 1 1 0 0 0 1 1 1
 1 1 1 0 1 1 0 1 1 1 1 1 1 0 0 1 0 1 1 0 0 1 1 1 1 0 1 1 1 1 0 1 0 1 1 1 1
 1 1 0 0 0 0 1 1 0 1 1 1 1 1 0 0 0 1 1 1 1 1 0 1 1 0 0 0 1 0 0 0 0 1 0 1 0
 1 0 1 1 1 1 1 1 0 1 1 0 1 0 1 0 1 1 0 1 0 0 1 1 0 0 0 1 1 1 0 0 1 0 1 1 1
 0 0 0 0 1 0 0 0 1 1 1 0 1 1 1 0 1 0 1 1 1 1 0 0 0 1 1 1 0 1 1 1 1 1 1 1 1
 1 0 1 0 0 0 1 1 1 1 1 1 0 1 0 

In [37]:
model = LinearSVC()
model.fit(X_train,y_train)



LinearSVC()

In [38]:
 # predict
y_pred = model.predict(X_test)

In [39]:
 # confusion matrix and accuracy

from sklearn import metrics
from sklearn.metrics import classification_report 

print(f"Classification report for classifier {model}:\n"
       f"{metrics.classification_report(y_test, y_pred)}\n")

Classification report for classifier LinearSVC():
              precision    recall  f1-score   support

           0       0.56      0.51      0.54        80
           1       0.65      0.70      0.67       105

    accuracy                           0.62       185
   macro avg       0.61      0.60      0.60       185
weighted avg       0.61      0.62      0.61       185




In [40]:

# Import necessary modules
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=7)
  
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=7)

In [41]:
 # predict
y_pred = knn.predict(X_test)

In [42]:
 # confusion matrix and accuracy

from sklearn import metrics
from sklearn.metrics import classification_report 

print(f"Classification report for classifier {model}:\n"
       f"{metrics.classification_report(y_test, y_pred)}\n")

Classification report for classifier LinearSVC():
              precision    recall  f1-score   support

           0       0.82      0.11      0.20        80
           1       0.59      0.98      0.74       105

    accuracy                           0.61       185
   macro avg       0.71      0.55      0.47       185
weighted avg       0.69      0.61      0.50       185




In [43]:
from sklearn.tree import DecisionTreeClassifier
clf_model = DecisionTreeClassifier(criterion="gini", random_state=42,max_depth=3, min_samples_leaf=5)   
clf_model.fit(X_train,y_train)

DecisionTreeClassifier(max_depth=3, min_samples_leaf=5, random_state=42)

In [46]:
y_predict = clf_model.predict(X_test)


In [47]:
 # confusion matrix and accuracy

from sklearn import metrics
from sklearn.metrics import classification_report 

print(f"Classification report for classifier {clf_model}:\n"
       f"{metrics.classification_report(y_test, y_pred)}\n")

Classification report for classifier DecisionTreeClassifier(max_depth=3, min_samples_leaf=5, random_state=42):
              precision    recall  f1-score   support

           0       0.82      0.11      0.20        80
           1       0.59      0.98      0.74       105

    accuracy                           0.61       185
   macro avg       0.71      0.55      0.47       185
weighted avg       0.69      0.61      0.50       185




In [32]:
joblib.dump(model, 'models.dat')
print('Model saved : {}'.format('models.dat'))


Model saved : models.dat
